### ISSUE TITLE
request help: 关于对wasm的支持

### ISSUE THREAD

**Issue by SRCchen** [apache/apisix-ingress-controller#1004]
### Issue description

在kind中部署的kubernetes集群,将wasm挂载到apisix容器的`/usr/local/apisix/wasm/`目录下,出现报错

```shell
2022/05/07 07:12:43 [error] 50#50: failed to new instance: unknown import: `env::proxy_continue_stream` has not been defined
2022/05/07 07:12:43 [error] 50#50: *1 [lua] plugin.lua:110: load_plugin(): failed to load plugin [wasm_log] err: failed to load wasm plugin, context: init_worker_by_lua*
2022/05/07 07:12:43 [warn] 50#50: *1 [lua] plugin.lua:223: load_stream(): new plugins: {"ip-restriction":true,"mqtt-proxy":true,"limit-conn":true}, context: init_worker_by_lua*
2022/05/07 07:12:43 [warn] 50#50: *4 stream [lua] plugin.lua:223: load_stream(): new plugins: {"ip-restriction":true,"limit-conn":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2022/05/07 07:12:43 [error] 51#51: failed to new instance: unknown import: `env::proxy_continue_stream` has not been defined
2022/05/07 07:12:43 [error] 51#51: *2 [lua] plugin.lua:110: load_plugin(): failed to load plugin [wasm_log] err: failed to load wasm plugin, context: init_worker_by_lua*
2022/05/07 07:12:43 [warn] 51#51: *2 [lua] plugin.lua:223: load_stream(): new plugins: {"ip-restriction":true,"mqtt-proxy":true,"limit-conn":true}, context: init_worker_by_lua*
2022/05/07 07:12:43 [warn] 51#51: *55 stream [lua] plugin.lua:223: load_stream(): new plugins: {"ip-restriction":true,"limit-conn":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2022/05/07 07:12:43 [error] 54#54: failed to new instance: unknown import: `env::proxy_continue_stream` has not been defined
2022/05/07 07:12:43 [error] 54#54: *3 [lua] plugin.lua:110: load_plugin(): failed to load plugin [wasm_log] err: failed to load wasm plugin, context: init_worker_by_lua*
```
以下为apisix-ingress-controller的报错。
```shell
GIN] 2022/05/07 - 15:22:05 | 200 |       41.37µs |      10.244.1.1 | GET      "/healthz"
2022-05-07T15:22:06+08:00	error	apisix/route.go:164	failed to create route: unexpected status code 400; error message: {"error_msg":"unknown plugin [wasm_log]"}
```
使用proxy_wasm:0.1 的rust sdk 似乎能成功加载
```shell
2022/05/07 07:41:51 [warn] 54#54: *2 [lua] plugin.lua:173: load(): new plugins: {"limit-req":true,"hmac-auth":true,"cors":true,"authz-keycloak":true,"wasm_log":{"http_request_phase":"access","priority":7999,"name":"wasm_log","file":"\/usr\/local\/apisix\/wasm\/forwardauth.wasm"},"consumer-restriction":true,"http-logger":true,"traffic-split":true,"key-auth":true,"ip-restriction":true,"jwt-auth":true,"grpc-transcode":true,"request-id":true,"uri-blocker":true,"basic-auth":true,"ext-plugin-post-req":true,"wolf-rbac":true,"ext-plugin-pre-req":true,"prometheus":true,"openid-connect":true,"fault-injection":true,"redirect":true,"limit-count":true,"gzip":true,"authz-casbin":true,"proxy-rewrite":true,"tcp-logger":true,"proxy-cache":true,"response-rewrite":true,"batch-requests":true,"syslog":true,"zipkin":true,"echo":true,"udp-logger":true,"sls-logger":true,"ua-restriction":true,"proxy-mirror":true,"serverless-pre-function":true,"real-ip":true,"limit-conn":true,"request-validation":true,"kafka-logger":true,"referer-restriction":true,"serverless-post-function":true,"node-status":true,"api-breaker":true}, context: init_worker_by_lua*
```
但是无法正常运行,报错如下:
```shell
022/05/07 07:46:36 [emerg] 50#50: *11727 panicked at 'unexpected status: 1', /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/proxy-wasm-0.1.4/src/hostcalls.rs:261:23, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "web.test.com"
2022/05/07 07:46:36 [error] 50#50: failed to call function: wasm trap: wasm `unreachable` instruction executed
2022/05/07 07:46:36 [error] 50#50: *11727 [lua] wasm.lua:76: phase_func(): wasm_log: failed to run wasm plugin: failed to run proxy_on_http_request_headers, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "web.test.com"
2022/05/07 07:46:36 [warn] 50#50: *11727 [lua] plugin.lua:750: run_plugin(): wasm_log exits with http status code 503, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "web.test.com"
2022/05/07 07:46:36 [emerg] 50#50: *11727 panicked at 'already borrowed: BorrowMutError', /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/proxy-wasm-0.1.4/src/dispatcher.rs:360:54, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "web.test.com"
2022/05/07 07:46:36 [error] 50#50: failed to call function: wasm trap: wasm `unreachable` instruction executed
2022/05/07 07:46:36 [error] 50#50: *11727 [lua] wasm.lua:112: phase_func(): wasm_log: failed to run wasm plugin: failed to run proxy_on_http_response_headers, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "web.test.com"
2022/05/07 07:46:36 [error] 50#50: failed to call function: wasm trap: wasm `unreachable` instruction executed
2022/05/07 07:46:36 [error] 50#50: failed to mark context 2 as done, rc: -1
2022/05/07 07:46:36 [error] 50#50: failed to call function: wasm trap: wasm `unreachable` instruction executed
2022/05/07 07:46:36 [error] 50#50: failed to delete context 2, rc: -1
```
删除apisix route  重新apply后, 报错信息会变成如下:
```shell
2022/05/07 07:52:28 [error] 51#51: *24609 [lua] wasm.lua:70: phase_func(): wasm_log: failed to fetch wasm plugin ctx: failed to run proxy_on_configure, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "web.test.com"
2022/05/07 07:52:28 [warn] 51#51: *24609 [lua] plugin.lua:750: run_plugin(): wasm_log exits with http status code 503, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "web.test.com"
2022/05/07 07:52:28 [error] 51#51: failed to call function: wasm trap: wasm `unreachable` instruction executed
2022/05/07 07:52:28 [error] 51#51: failed to create context 3, rc: -1
2022/05/07 07:52:28 [error] 51#51: *24609 [lua] wasm.lua:106: phase_func(): wasm_log: failed to fetch wasm plugin ctx: failed to run proxy_on_configure, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "web.test.com"
```

这两个版本的插件在envoy的docker-compose中都运行正常,请问是我有什么地方配的不对吗

### Environment

helm chart version： 0.9.1
kubernetes version: 1.20.15
rust  version: 1.60.0
proxy-wasm: 0.2

**Comment by tao12345666333** [comment]
@spacewander  PTAL
thanks

**Comment by spacewander** [comment]
> failed to new instance: unknown import: `env::proxy_continue_stream` has not been defined

Can you provide a minimal reproducible example of the rust code so we can reproduce it? And the version of rust SDK.

**Comment by SRCchen** [comment]
`proxy_wasm_rust_sdk` version: 0.2

cargo.toml
```toml
[package]
name = "wasmdemo"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]


[dependencies]
log = "0.4"
proxy-wasm = "0.2"
```

example code:
```rust
use log::trace;
use proxy_wasm::traits::*;
use proxy_wasm::types::*;
use std::time::Duration;

proxy_wasm::main! {{
    proxy_wasm::set_log_level(LogLevel::Trace);
    proxy_wasm::set_http_context(|_, _| -> Box<dyn HttpContext> { Box::new(HttpAuthRandom) });
}}

struct HttpAuthRandom;

impl HttpContext for HttpAuthRandom {
    fn on_http_request_headers(&mut self, _: usize, _: bool) -> Action {
        self.dispatch_http_call(
            "httpbin",
            vec![
                (":method", "GET"),
                (":path", "/bytes/1"),
                (":authority", "httpbin.org"),
            ],
            None,
            vec![],
            Duration::from_secs(5),
        )
        .unwrap();
        Action::Pause
    }

    fn on_http_response_headers(&mut self, _: usize, _: bool) -> Action {
        self.set_http_response_header("Powered-By", Some("proxy-wasm"));
        Action::Continue
    }
}

impl Context for HttpAuthRandom {
    fn on_http_call_response(&mut self, _: u32, _: usize, body_size: usize, _: usize) {
        if let Some(body) = self.get_http_call_response_body(0, body_size) {
            if !body.is_empty() && body[0] % 2 == 0 {
                trace!("Access granted.");
                self.resume_http_request();
                return;
            }
        }
        trace!("Access forbidden.");
        self.send_http_response(
            403,
            vec![("Powered-By", "proxy-wasm")],
            Some(b"Access forbidden.\n"),
        );
    }
}
```

**Comment by spacewander** [comment]
Look like the sdk imports some functions which are not in the [spec](https://github.com/proxy-wasm/spec/tree/master/abi-versions/vNEXT) : https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/blob/c32d380ca6c9b1afac38a3841be99c37af2698bf/proxy_wasm_externs.h#L58

**Comment by spacewander** [comment]
Could you rewrite the plugin with `set_root_context`:

https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/fb7c953adcba19adb79b4e1885cbb532a2fbad22/examples/http_body.rs#L20

https://github.com/api7/wasm-nginx-module/blob/733e5d349235422f6eaa9cbeb2a3d38751bc2342/t/testdata/rust/fault_injection.rs#L24

and run it with older proxy-wasm-rust-sdk?

**Comment by SRCchen** [comment]
尝试用0.1版本的sdk时,出现了报错` panicked at 'already borrowed: BorrowMutError'`
完整报错:
```text
2022/05/09 09:08:31 [emerg] 51#51: *2043 panicked at 'unexpected status: 2', /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/proxy-wasm-0.1.4/src/hostcalls.rs:261:23, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "web.test.com"
2022/05/09 09:08:31 [error] 51#51: failed to call function: wasm trap: wasm `unreachable` instruction executed
2022/05/09 09:08:31 [error] 51#51: *2043 [lua] wasm.lua:76: phase_func(): wasm_log: failed to run wasm plugin: failed to run proxy_on_http_call_response, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "web.test.com"
2022/05/09 09:08:31 [warn] 51#51: *2043 [lua] plugin.lua:750: run_plugin(): wasm_log exits with http status code 503, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "web.test.com"
2022/05/09 09:08:31 [emerg] 51#51: *2043 panicked at 'already borrowed: BorrowMutError', /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/proxy-wasm-0.1.4/src/dispatcher.rs:360:54, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "web.test.com"
2022/05/09 09:08:31 [error] 51#51: failed to call function: wasm trap: wasm `unreachable` instruction executed
2022/05/09 09:08:31 [error] 51#51: *2043 [lua] wasm.lua:112: phase_func(): wasm_log: failed to run wasm plugin: failed to run proxy_on_http_response_headers, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "web.test.com"
2022/05/09 09:08:31 [error] 51#51: failed to call function: wasm trap: wasm `unreachable` instruction executed
2022/05/09 09:08:31 [error] 51#51: failed to mark context 2 as done, rc: -1
2022/05/09 09:08:31 [error] 51#51: failed to call function: wasm trap: wasm `unreachable` instruction executed
2022/05/09 09:08:31 [error] 51#51: failed to delete context 2, rc: -1
2022/05/09 09:08:32 [error] 51#51: failed to call function: wasm trap: wasm `unreachable` instruction executed
```
似乎是因为在`on_http_call_response` 中使用了`get_http_call_response_header`
代码如下：
```rust
use log::trace;
use log::{warn,info};
use proxy_wasm::traits::*;
use proxy_wasm::types::*;
use std::time::Duration;
use serde_json::Value;
use url::Url;

#[no_mangle]
pub fn _start() {
    proxy_wasm::set_log_level(LogLevel::Trace);
    proxy_wasm::set_root_context(|_| -> Box<dyn RootContext> { 
        Box::new(HttpAuthForwardRoot{
            config: FilterConfig{
                host: "".to_string(),
            }
        }) 
    });
}

struct HttpAuthForwardRoot {
    config: FilterConfig
}

struct HttpAuthForwardFilter{
    context_id: u32,
    config: FilterConfig, 
}

struct  FilterConfig {
    host: String,
}

impl HttpContext for HttpAuthForwardFilter {
    fn on_http_request_headers(&mut self, _num_headers: usize) -> Action {
        let mut hs = vec![];
        let authurl = Url::parse(self.config.host.as_str()).unwrap();

        hs.push((":scheme",authurl.scheme()));
        hs.push((":authority",authurl.host_str().unwrap()));
        hs.push((":path",authurl.path()));
        hs.push((":method","GET"));

        self.dispatch_http_call(
            authurl.host_str().unwrap(),
            hs,
            None,
            vec![],
            Duration::from_secs(5),
        )
        .unwrap();
        for (name, value) in &self.get_http_request_headers() {
            info!("::::H[{}] -> {}: {}", self.context_id, name, value);
        }
        Action::Pause
    }

    fn on_http_response_headers(&mut self, _num_headers: usize) -> Action {
        self.set_http_response_header("Powered-By", Some("proxy-wasm"));
        Action::Continue
    }
}

impl Context for HttpAuthForwardFilter {
    fn on_http_call_response(&mut self, _token_id: u32, _num_headers: usize, body_size: usize, _num_trailers: usize) {
        
        let s = self.get_http_call_response_header("Content-Type").unwrap();
        info!("{}",s);
        
        if let Some(body) = self.get_http_call_response_body(0, body_size) {
            if !body.is_empty() && body[0] % 2 == 0 {
                trace!("Access granted.");
                self.resume_http_request();
                return;
            }
        }

        trace!("Access forbidden.");
        self.send_http_response(
            403,
            vec![("Powered-By", "proxy-wasm")],
            Some(b"Access forbidden.\n"),
        );
    }
}


impl RootContext for HttpAuthForwardRoot {
    fn on_configure(&mut self, _plugin_configuration_size: usize) -> bool {
        if self.config.host == "" {
            match self.get_configuration() {
                Some(config_bytes) => {
                    let cfg:Value = serde_json::from_slice(config_bytes.as_slice()).unwrap();
                    self.config.host = cfg.get("host")
                    .unwrap()
                    .as_str()
                    .unwrap()
                    .to_string();

                }
                None => {
                    warn!("No config");
                }
            }
        }
    true
    }
    fn create_http_context(&self, context_id: u32) -> Option<Box<dyn HttpContext>> {
        info!("::::create_http_context,context_id: {} ,host: {}",context_id,self.config.host);
        Some(Box::new(HttpAuthForwardFilter{
            context_id,
            config: FilterConfig{
                host: self.config.host.clone(),
                }
            }))
        }
    fn get_type(&self) -> Option<ContextType> {
        Some(ContextType::HttpContext)
    }
}

impl Context for HttpAuthForwardRoot {}
```

**Comment by spacewander** [comment]
Turn out I forgot to implement `get_http_call_response_header`. Does it work well after removing it?

**Comment by SRCchen** [comment]
> Turn out I forgot to implement `get_http_call_response_header`. Does it work well after removing it?

去掉`get_http_call_response_header`后可以正常运行

**Comment by spacewander** [comment]
Consider solved?
