### ISSUE TITLE
bug: ingress controller panic after delete ingress resource

### ISSUE THREAD

**Issue by nic-6443** [apache/apisix-ingress-controller#855]
### Issue description

APISIX Ingress Controller will panic while handle ingress delete event, panic log:
```
2022-01-03T13:26:58Z	debug	ingress/ingress.go:346	ingress delete event arrived	{"final state": {}}
2022-01-03T13:26:58Z	debug	ingress/ingress.go:138	translated ingress resource to a couple of routes, upstreams and pluginConfigs	{"ingress": {}, "routes": [{"id":"46b67ef7","name":"ingress_httpbin.org_/ip","desc":"Created by apisix-ingress-controller, DO NOT modify it manually","labels":{"managed-by":"apisix-ingress-controller"},"host":"httpbin.org","uris":["/ip"],"upstream_id":"3d913da8"}], "upstreams": [{"id":"3d913da8","name":"ingress-apisix-e2e-tests-default-41670000_httpbin-service-e2e-test_80","desc":"Created by apisix-ingress-controller, DO NOT modify it manually","labels":{"managed-by":"apisix-ingress-controller"},"type":"roundrobin","nodes":[{"host":"172.30.45.175","port":80,"weight":100}],"scheme":"http"}], "ssl": null, "pluginConfigs": null}
2022-01-03T13:26:58Z	debug	apisix/route.go:180	try to delete route	{"id": "46b67ef7", "name": "ingress_httpbin.org_/ip", "cluster": "default", "url": "http://apisix-service-e2e-test:9180/apisix/admin/routes"}
2022-01-03T13:26:58Z	debug	apisix/upstream.go:171	try to delete upstream	{"id": "3d913da8", "name": "ingress-apisix-e2e-tests-default-41670000_httpbin-service-e2e-test_80", "cluster": "default", "url": "http://apisix-service-e2e-test:9180/apisix/admin/upstreams"}
2022-01-03T13:26:58Z	warn	ingress/ingress.go:231	sync ingress failed, will retry	{"object": {"Type":3,"Object":{"Key":"ingress-apisix-e2e-tests-default-41670000/ingress-v1-lb","GroupVersion":"networking/v1","OldObject":null},"Tombstone":{}}, "error": "ingress.networking.k8s.io \"ingress-v1-lb\" not found"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x161d20a]

goroutine 297 [running]:
github.com/apache/apisix-ingress-controller/pkg/ingress.(*ingressController).handleSyncErr(0xc0000cdae0, {0x16c6e40, 0xc000246ae0}, {0x0, 0x0})
	/Users/nic/GolandProjects/apisix-ingress-controller/pkg/ingress/ingress.go:237 +0x82a
github.com/apache/apisix-ingress-controller/pkg/ingress.(*ingressController).runWorker(0xc0000cdae0, {0x1cb2430, 0xc000244280})
	/Users/nic/GolandProjects/apisix-ingress-controller/pkg/ingress/ingress.go:81 +0x92
created by github.com/apache/apisix-ingress-controller/pkg/ingress.(*ingressController).run
	/Users/nic/GolandProjects/apisix-ingress-controller/pkg/ingress/ingress.go:68 +0x253
```

### Environment

use code in master branch

### Minimal test code / Steps to reproduce

/

### Actual result

/

### Error log

/

**Comment by tao12345666333** [comment]
Can you provide a minimal steps to reproduce?

**Comment by tao12345666333** [comment]
@nic-6443 any update?

**Comment by champly** [comment]
I meet the same probelm, because the `EventDelete` will cause ingressLister got with namespace and name error, variable `ing` is nil.
