### ISSUE TITLE
request help:  apisix/cluster.go:343	cluster default now is ready, cost time 608.392498ms

### ISSUE THREAD

**Issue by PGDream** [apache/apisix-ingress-controller#934]
### Issue description

i see https://github.com/apache/apisix-ingress-controller/pull/872  merged to master, pull master branch to local and build dockerfile,docker mirrors address: zengqiang/apisix-ingress-controller:1.4.1, `restart install apisix-ingress-controller error log`:

```
2022-03-25T09:36:32+08:00 debug apisix/consumer.go:109 try to list consumers in APISIX {"cluster": "default", "url": "http://apisix-admin.ingress-apisix.svc.cluster.local:9180/apisix/admin/consumers"}
2022-03-25T09:36:32+08:00 info gin@v1.7.7/context.go:168 path: /healthz, status: 200, method: GET, query: , ip: 172.20.0.65, user-agent: kube-probe/1.20+, errors: , cost: 35.715µs
2022-03-25T09:36:32+08:00 debug apisix/pluginconfig.go:112 try to list pluginConfig in APISIX {"cluster": "default", "url": "http://apisix-admin.ingress-apisix.svc.cluster.local:9180/apisix/admin/plugin_configs"}
2022-03-25T09:36:32+08:00 info apisix/cluster.go:164 cache synced {"cost_time": "608.299617ms", "cluster": "default"}
2022-03-25T09:36:32+08:00 warn apisix/cluster.go:343 cluster default now is ready, cost time 608.392498ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x18a37b6]

goroutine 29 [running]:
github.com/apache/apisix-ingress-controller/pkg/ingress.(*Controller).newApisixRouteController(0xc0003fe000, 0xc0000de780)
 /build/pkg/ingress/apisix_route.go:49 +0x256
github.com/apache/apisix-ingress-controller/pkg/ingress.(*Controller).initWhenStartLeading(0xc0003fe000)
 /build/pkg/ingress/controller.go:282 +0x12fe
github.com/apache/apisix-ingress-controller/pkg/ingress.(*Controller).run(0xc0003fe000, 0x1fd0510, 0xc0000c7a00)
 /build/pkg/ingress/controller.go:440 +0x76d
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
 /go/pkg/mod/k8s.io/client-go@v0.22.4/tools/leaderelection/leaderelection.go:211 +0x11b
```

### Environment

- k8s 1.20.11-aliyun.1
- apisix 2.12
- apisix-ingress-controller 1.4

**Comment by tao12345666333** [comment]
Have you created some custom resources?

**Comment by PGDream** [comment]
> 

NO , not create CRD 
default with ingress

**Comment by tao12345666333** [comment]
Is there any special configuration? Is it possible to provide steps to reproduce
